# Generated by Django 5.0.2 on 2024-03-08 00:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='descripcion',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tareas',
            name='titulo',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
